name: Refill test cheques

on:
  workflow_dispatch:

jobs:
  refill:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - name: Checkout the june-cheque repo
      uses: actions/checkout@v2
      with:
        path: june-cheque

    - name: install needed packages
      run: |
        sudo apt-get install python3
        sudo apt-get install python3-pip
        sudo apt-get install python3-duniterpy
        pip3 install silkaj

    - name: do refill
      run: |
        cd june-cheque
        tfile=$(mktemp  /tmp/.XXXXXXXXX)
        chmod 600 $tfile
        python3 ./save_and_load_private_key_file_pubsec.py "${GITHUBACCOUNT_IDENTIFIER}" "${GITHUBACCOUNT_KEY}" "$tfile"
        silkaj -af --file "$tfile" money transfer -c "refill" -a 1 -r "DR6uUwvcfxJZvw6mi4KQny5Ex7eiNTAfzgMw15DG1WLG:HAe" -r "7t6q4v6khqCSDguucuU2iBhyE3vM53vLb82QaERvdNYt:DNA" -r "HjFVXVsoyvJ9FoLq8i6XLchtnTBVtqRCqgYtvB6vgipA:DsM" -r "3Yir21RRKoy2DFTnzCsbCYnsuLmVLfCbh8kiHoD9cjkp:ErQ" -r "EY1EX78TxeahmPxttQVYMKiiQE4N23mEB9BgnnfsifRH:6Wm" -r "5P1pNny2x6tHvbP7UV8HkQL4YnBkfJVgcwsSfVjyMgHG:Aaw" -y
      env:
        GITHUBACCOUNT_IDENTIFIER: ${{ secrets.GITHUBACCOUNT_IDENTIFIER }}
        GITHUBACCOUNT_KEY: ${{ secrets.GITHUBACCOUNT_KEY }}

