name: Test debian package creation

on:
  workflow_dispatch:




jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the june-cheque repo
      uses: actions/checkout@v2
      with:
        path: june-cheque

    - name: create the package
      run: |
        cd june-cheque
        make pkg-debi

    - name: install the package
      run: |
        cd june-cheque
        sudo dpkg -i *.deb

    - name: run help of the package
      run: |
        june-cheque-create -h
